name: Visual Regression
on:
  pull_request:
    types: [ready_for_review]
jobs:
  visual-regression:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        # Check whether components were changed.
        # Then below, we can only run steps if there's something to test.
      - uses: dorny/paths-filter@v2
        id: component_changes
        with:
          filters: |
            components:
              - 'components/**'
      - name: Install Node.js
        if: steps.component_changes.outputs.components == 'true'
        uses: actions/setup-node@v2
        with:
          node-version: 16.13
      - name: Install
        if: steps.component_changes.outputs.components == 'true'
        run: npm ci
        env:
          YALESITES_BUILD_TOKEN: ${{ secrets.YALESITES_BUILD_TOKEN }}
      - name: Build storybook
        if: steps.component_changes.outputs.components == 'true'
        run: npm run storybook:build
      - name: Run Percy Tests
        if: steps.component_changes.outputs.components == 'true'
        run: npm run visreg:ci
        env:
          PERCY_TOKEN: ${{ secrets.PERCY_TOKEN }}
  deploy-pr-component-library:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      # Sets the branch name as environment variable.
      - shell: bash
        run: echo "##[set-output name=branch;]$(echo ${GITHUB_REF#refs/heads/})"
        id: extract_branch
      # Deploys to Netlify.
      - uses: jsmrcaga/action-netlify-deploy@master
        with:
          node-version: 16.13
          NETLIFY_AUTH_TOKEN: ${{ secrets.YALESITES_BUILD_TOKEN }}
          NETLIFY_SITE_ID: ${{ secrets.NETLIFY_SITE_ID }}
          deploy_alias: ${{ env.steps.extract_branch.outputs.branch }}
      # Creates a status check with link to preview.
      - name: Status check
        uses: Sibz/github-status-action@v1
        with:
          authToken: ${{ secrets.GITHUB_TOKEN }}
          context: Netlify preview
          state: success
          target_url: https://${{ env.steps.extract_branch.outputs.branch }}--dev-component-library-twig.netlify.app
